BaseUrl: "http://scotttactical.com/"
LanguageCode: "en-us"
Title: "Scott Tactical"
Theme: "beg"

Params:
  Author: "Scott Tactical"
  DateForm: "Mon, 02 Jan 2006 15:04:05 MST"
  GoogleAnalyticsUserID: "UA-53440065-2"
  Facebook: "100005012745496"
  Twitter: "scott_tactical"
  Github: "solvire"
  ShowRelatedPost: True
  Disqus: "unresolved"
  SyntaxHighlightTheme: "github.min.css"
  GalleryBaseUrl: "http://img.scotttactical.com/images/gallery/"

Indexes:
  tag: "tags"

permalinks:
  post: post/:slug/
  gallery: gallery/:slug/

MetadataFormat: "yaml"
