BaseUrl: "http://scotttactical.com/"
LanguageCode: "en-us"
Title: "Scott Tactical"
# Theme: "beg"
Theme: "hugo_theme_beg"
# Theme: "hugo-nuo"
disqusShortname: "scotttactical"

Params:
  Author: "Scott Tactical"
  DateForm: "Mon, 02 Jan 2006 15:04:05 MST"
  ISO8601: "2006-01-02T15:04:05-08:00"
  GoogleAnalyticsUserID: "UA-53440065-2"
  Facebook: "100005012745496"
  Twitter: "scott_tactical"
  Github: "solvire"
  ShowRelatedPost: True
  Disqus: "scotttactical"
  SyntaxHighlightTheme: "github.min.css"
  GalleryBaseUrl: "http://img.scotttactical.com/images/gallery/"

Indexes:
  tag: "tags"
  gallery: "galleries"
  news: "news"

permalinks:
  post: post/:slug/
  gallery: gallery/:slug/
  news: :year/:month/:slug/

MetadataFormat: "yaml"
