BaseUrl: "https://scotttactical.com/"

ignoreFiles:
  - content/posts/\.*
  - content/portfolio/\.*
  - content/product/\.*
  - content/sketch/\.*
  - content/en/\.*
  - content/fr/\.*


LanguageCode: "en-us"
Title: "Scott Tactical"
# Theme: "beg"
Theme: "hugo_theme_beg"
# Theme: "hugo-nuo"
disqusShortname: "scotttactical"
googleAnalytics: "UA-53440065-2" # Optional


paginate: 3
languageCode: en
DefaultContentLanguage: en

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
taxonomies:
  category: categories
  tag: tags
  series: series
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
    disableInlineCSS: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true


Params:
  Author: "Scott Tactical"
  DateForm: "Mon, 02 Jan 2006 15:04:05 MST"
  ISO8601: "2006-01-02T15:04:05-08:00"
  GoogleAnalyticsUserID: "UA-53440065-2"
  Facebook: "100005012745496"
  Twitter: "scott_tactical"
  Github: "solvire"
  ShowRelatedPost: True
  Disqus: "scotttactical"
  SyntaxHighlightTheme: "github.min.css"
  GalleryBaseUrl: "http://img.scotttactical.com/images/gallery/"

Indexes:
  tag: "tags"
  gallery: "galleries"
  # news: "news"

permalinks:
  post: post/:slug/
  gallery: gallery/:slug/
  news: :year/:month/:slug/

MetadataFormat: "yaml"


copyright: >-
  Copyright © 2014–2019, Scott Tactical; all rights reserved.
